version: "3.9"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    image: podverse-database:latest
    container_name: podverse_database
    environment:
      POSTGRES_USER: podverse_admin
      POSTGRES_PASSWORD: testest
      POSTGRES_DB: podverse_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - podverse-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: podverse-backend:latest
    container_name: podverse_backend
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://podverse_admin:testest@database:5432/podverse_db
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: podverse_admin
      DATABASE_PASSWORD: testest
      DATABASE_NAME: podverse_db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/scripts:/app/scripts
      - ./backend/app:/app/app

    depends_on:
      - database
    networks:
      - podverse-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: podverse_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    networks:
      - podverse-network


volumes:
  pgdata:

networks:
  podverse-network:
    driver: bridge
