version: "3.9"

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    image: podverse-database:latest
    container_name: podverse_database
    environment:
      POSTGRES_USER: podverse_admin
      POSTGRES_PASSWORD: testest
      POSTGRES_DB: podverse_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - podverse-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: podverse-backend:latest
    container_name: podverse_backend
    ports:
      - "8000:8000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://podverse_admin:testest@database:5432/podverse_db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/scripts:/app/scripts
      - ./backend/app:/app/app
    depends_on:
      - database
    networks:
      - podverse-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: podverse_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    networks:
      - podverse-network

  ai:
    build:
      context: .
      dockerfile: Dockerfile.ai
    image: podverse-ai:latest
    container_name: podverse_ai
    ports:
      - "5050:5050"
    volumes:
      - ./:/app
    depends_on:
      - backend
      - ai_db
    environment:
      FLASK_ENV: development
      BACKEND_URL: http://backend:8000
      DATABASE_URL: postgresql://ai_user:ai_pass@ai_db:5432/ai_profiles
      PYTHONPATH: /app
      PODVERSE_BACKEND_PATH: /app/backend/app
    networks:
      - podverse-network

  ai_db:
    image: postgres:15
    container_name: podverse_ai_db
    environment:
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_pass
      POSTGRES_DB: ai_profiles
    volumes:
      - ai_pgdata:/var/lib/postgresql/data
      - ./ai/db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql  
    ports:
      - "5433:5432"
    networks:
      - podverse-network

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ${OLLAMA_MODEL_PATH:-./.ollama}:/root/.ollama  # Default fallback
    ports:
      - "11435:11434"
    restart: always
    networks:
      - podverse-network



volumes:
  pgdata:
  ai_pgdata:

networks:
  podverse-network:
    driver: bridge
